### ISSUE TITLE
Responder State IDs

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#100]
Presently, Responder State nodes are linked to a single output node on the Responder. Additionally, they can be linked to one another and theoretically be included in the Responder. While this is sufficient for general use cases, for Responder states to be used in Python via `ptAttribResponder`, the Responder State's index must be known by the Python script.

I envision this being fixed by removing the States output node and replacing it with a single node socket that only accepts one state. The socket will report the Responder State's index for use in scripts. Additionally, states MUST be connected to the Responder's output in order to be exported. States can still trigger other states, however, this will be done via a different node socket.

**Comment by Deledrius** [comment]
I'm not sure I understand the suggestion for the new system.  Do you mean a single socket for each state, with each state dynamically adding a new socket below it (and next in index order)?

**Comment by Hoikas** [comment]
Correct

**Comment by Deledrius** [comment]
Do we have guaranteed access to socket order?
