### ISSUE TITLE
Shared lightmap on multi-user materials

### ISSUE THREAD

**Issue by Jrius** [H-uru/korman#132]
Heya !
On the 0.07 version of Korman, it seems lightmaps are baked directly to the material(s) the object is using. This will cause issues if another object uses the same material (resulting in the second object using the lightmap of the first object). Korman should leave the original material untouched, and instead bake the lightmap to a copy of this material. For now, I can work around this issue by making a single-user copy of the material in Blender.

(I see the current version of Korman has a slightly different lightmapping modifier - I tried to replicate the issue on this version, but couldn't get a test Age to export at all, so sorry if this multi-user material bug has already been fixed :P )

**Comment by Hoikas** [comment]
It looks like the material code pretty well assumes that every material is single user. That's not a good thing.

**Comment by Deledrius** [comment]
Thank you for this bug report.  It's great to get things like this caught before a release.  ;)
