### ISSUE TITLE
DAG zero

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#137]
Blender's whining about `DAG zero` messes up our beautiful progress screen. We should use Windows's console API to store the cursor position when a progress step begins and reset the cursor position every time we go to print.

**Comment by Deledrius** [comment]
This sounds like evil HAX.  Be sure to gate it behind an OS check at least...

**Comment by Hoikas** [comment]
```python
if sys.platform == "win32":
    evil()
else:
    ansi_escape()
```
