### ISSUE TITLE
Add support for normal/bump mapping

### ISSUE THREAD

**Issue by dpogue** [H-uru/korman#15]
Plasma's way of doing this isn't totally straight forward, and I'm not sure how it would end up hooking up in Blender.

**Comment by Deledrius** [comment]
Blender has straightforward options to use a texture as a bump or normal map, so at the very least those should be used.  Translating that to Plasma is the challenge.  It could be really nice to have automated normal and bump map baking, but I suspect that would be an advanced feature.

From [Blender: Bump and Normal Maps] (http://www.blender.org/manual/render/blender_render/textures/influence/material/bump_and_normal.html):
- When using a Bump map, map the texture to Normal and enable No RGB.
- When using a Normal map, map the texture to Normal.

**Comment by Hoikas** [comment]
This is in progress in #50

**Comment by Hoikas** [comment]
Closed by #50
