### ISSUE TITLE
SDL Version 0 Problems

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#153]
Per cjkelly1 (http://forums.openuru.org/viewtopic.php?f=108&t=1029&start=30#p9630), there are issues with the "default" Korman SDL file, which exports with "VERSION 0", and MOSS. A change to VERSION 1 seems to fix this.

**Comment by Hoikas** [comment]
SDL Version 0 is perfectly valid, MOSS is just whining for no good reason. :wink:
