### ISSUE TITLE
World Data-Block Issue

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#158]
Noticed after opening an old blend, it seems that if said blend doesn't have a world data-block selected, then Korman shows nothing in the World window (ie Age and export settings).

Could Korman auto-select an orphaned data-block (which, for some reason, is what happened in this case), create a new world block automatically if none exists, and/or give the option to create/choose one like in Blender Render?

![WorldProb01](https://user-images.githubusercontent.com/40325124/67573887-5c7c6a00-f707-11e9-930f-2b6a5bed888b.jpg)

**Comment by Hoikas** [comment]
Fixed by eb8aa53.
