### ISSUE TITLE
Lamp Texture Slot Error

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#163]
This was for recreating the Great Zero beam. Setting the texture on the area lamp produces this error on export:

"AttributeError: 'LampTextureSlot' object has no attribute 'use_map_color_diffuse'"

**Comment by Hoikas** [comment]
There were a lot of assumptions that got added about Texture Slots being attached to valid Materials. Lamp textures have no Material, so boom. I think I sniffed them all out, but there might be some more snakes in the grass...
