### ISSUE TITLE
Random Sound Modifier

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#165]
Need to expose `plRandomSoundMod` for random background music stingers and kickable collision sound effects.

**Comment by Hoikas** [comment]
Incomplete bindings available at H-uru/libhsplasma#186 - they need to be completed before this feature can be completely implemented.

**Comment by Deledrius** [comment]
#212 has some work done for this already.

**Comment by Hoikas** [comment]
Bindings are now available.

**Comment by DoobesURU** [comment]
Forgive my usual cluelessness, but how does one get these bindings to try some exports? 😉
