### ISSUE TITLE
Version Setting for Object/Material/Texture

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#167]
Could there be a way to set the version of URU to which an object exports?  For example, the Linking Book meshes in PotS/CC won't need the "share" book texture that MOULa will need for certain books (such as the Teledahn book in the Baron's City Office). So two versions of the same object would be needed in such instances.

**Comment by Deledrius** [comment]
The setting for whether a book is currently sharable is in the xLinkingBookDefs, and is definitely one of those things that should be exposed to the PFM in the pending rewrite to xLinkingBookGUIPopup.  Perhaps I should open an issue there for collecting the things we need to expose for full compatibility.  With that fix, it would be a matter of exporting the correct tree for each version and not require an asset change.

**Comment by DoobesURU** [comment]
Yep, the GUI popup works nicely for both versions...however, the book clickable itself still has a share icon, even when in PotS. So it's not really a GUI thing, it's a mesh/material/texture thing.
