### ISSUE TITLE
Default py file settings if World data-block is lost and reformed

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#189]
So a small bug with exporting an Age py file. Here's how it happened for me:

* I added a second "World" data-block with different Age settings for testing the Great Tree Pub.
* Forgetting to click the "F" next to it to save the old data-block, it was cleared as orphan data.
* Noticing this, I re-added the data-block exactly as it was, with the same Age name as the py file.
* Despite this, while the re-added data-block does export the py file, it does not use the existing text block but the default py file settings.

EDIT: Checking the "Export" box for the Age py file does the trick, but not sure if that is how it's supposed to be. Also, the SDL seemed to export fine if that helps.

**Comment by Hoikas** [comment]
> Checking the "Export" box for the Age py file does the trick, but not sure if that is how it's supposed to be.

It looks like this is the intended behavior according to the `_pack_agesdl_hook()` method. It (eventually) checks the export checkbox and uses the default python if it's unchecked.
