### ISSUE TITLE
Rail Camera Keyframes

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#198]
It is currently possible to export rail cameras with less than two keyframes, causing the client to crash by deferencing a null pointer to the boundary keyframes. Korman should abort the export when this kind of invalid animation is supplied.

**Comment by DoobesURU** [comment]
#200 should hopefully do the trick, but it could do with some review by the experts. 😄

**Comment by Hoikas** [comment]
Closed by #200.
