### ISSUE TITLE
Day/night cycle animation support

### ISSUE THREAD

**Issue by dpogue** [H-uru/korman#204]
Day/Night cycles (or other animations spanning the duration of the day) are handled using plAgeGlobalAnims. Instead of being time or frame based, these animations run from their starting frame to their ending frame over the course of the Age's day length (slight simplification, since it involves SDLs and time of day percentages).

The goal is to add a new animation modifier to korman to flag these sorts of animations. It should also have a field for specifying which SDL variable controls the animation. The bindings already exist in PyHSPlasma.

**Tasks:**

- [ ] Set up a new korman modifier for "Day cycle animations"
  - It should take the name of an SDL variable that controls the animation progress
- [ ] Set up export code to export the animation as a plAgeGlobalAnim

**Comment by Hoikas** [comment]
This would probably make more sense as a single property on the animation modifier.

**Comment by dpogue** [comment]
Checkbox on the existing modifier for "Driven by SDL variable" that enables a textbox for the SDL varname?

**Comment by Hoikas** [comment]
I was thinking a single text field for the SDL variable--a blank input is a plain old ATC Anim.

**Comment by DoobesURU** [comment]
The above PR goes along the lines of what Hoikas was thinking for the modifier: a single text field entry. At the moment, it's only enabled when the "Loop Anim" option is selected. Not sure if that's how we want it?
