### ISSUE TITLE
Double Sided issues/feature request

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#206]
Since the addition of the new "Double Sided" feature (thank you!), I've noticed that any Ages brought in from 2.49b and PyPRP have this option on by default for **all** meshes, including colliders and regions. If left as it is now, those that wish to carry their Ages over from the old plugin may inadvertently and unknowingly add to their performance issues this way.

Is there a way to force this off when first opening a 2.49b file? On a related note, is there a way to add options to the toolbox to control this feature much like the Plasma Objects (Enable/Disable All, Enable/Disable Selection)? It would be useful to manually solve this problem and be able to toggle it for multiple objects that may need it, such as any foliage, banners, etc.

I actually tried the latter...and, not surprisingly, failed. I'm hoping it'll be relatively easy for you. 😄

**Comment by Hoikas** [comment]
I don't think we can detect when version of blender a file came from - we really only know when a file is being loaded. It also wouldn't catch cases of old blend files being appended or linked, I think. I've also noticed that importing .obj files will produce double-sided meshes. So, adding a toolbox operator is probably the way to go.

**Comment by DoobesURU** [comment]
Cool. We can add something to the "Update from PyPRP tutorial or the before exporting section and **hopefully** they'll notice and turn off DS for all objects before starting.

**Comment by Hoikas** [comment]
Closed by #209
