### ISSUE TITLE
Lighting Problems Since PR #210

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#228]
Working on the Pub's holiday additions, I have noticed a few things since #210:

- Having Shadeless checked on a mesh set with a modifier for a lightmap...and occasionally on a vertex colored mod...doesn't produce the full bright effect and, in fact, shadows the area anyway. Also, it appears, at least when a mesh has its scale animated (in this case, the candle flames on the menorah imported from the city), that shadeless also doesn't work.

- New materials, or perhaps meshes with newly added Bake Lighting modifiers, do not light properly despite having the same settings as existing (and properly lit) meshes and materials.

- While it doesn't show in the final export, meshes with an existing Col vertex paint are once again producing an unnecessary "autocolor" Vcol layer.

I'm still checking to see if there's anything else, but this is what's stuck out so far.

**Comment by DoobesURU** [comment]
Another observation: animated objects are also not lighting properly unless parented to an empty/dummy object.

**Comment by DoobesURU** [comment]
Update #2: So I tried a few things:

1. It looks like there were a few instances of `plasma_modifiers.lighting.rt_lights` in the materials and mesh export scripts. Was this meant to be `plasma_modifiers.lighting.force_rt_lights` as it says in the modifier?

2. While on the modifier, it seems to also be using the force_rt_lights bool value even if the modifier itself isn't active on a particular object. Adding the mod back and unchecking Force RT Lights seems to fix this for some objects. Still testing this on others.

**Comment by Hoikas** [comment]
Closing after #230
