### ISSUE TITLE
Object rotation issue

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#233]
So quite a few times now, I've notice that, when you want to have an object do a complete 360 degree rotation, two keyframes won't work. A third one needs to be added somewhere in between the first two to actually make the rotation go in URU (I usually use the 180 degree point).

Is this a Korman issue or possibly an URU issue?

**Comment by Hoikas** [comment]
This is a math thing - keyframes set your start and stop point, and the animation runs through the difference between those points. In the case of a two keyframe 360 degree rotation, your start and stop points are effectively the same, resulting a difference (and therefore animation of) zero. If you check Cyan's Ages, you'll see that they usually have three keyframes to do this kind of rotation :wink:

**Comment by DoobesURU** [comment]
Ah, then I guess I wasn't looking hard enough at existing stuff. Closing...
