### ISSUE TITLE
Ability to turn off LPMovable flag for animated lamps

### ISSUE THREAD

**Issue by dpogue** [H-uru/korman#264]
By default, all animated lamps are exported with the `kLPMovable` flag, which causes the lamps to be applied to all objects in the scene at runtime.

This poses an issue for objects that are trying to use light groups to restrict light behaviour to specific objects, since the engine ignores the light group at runtime leading to unintended lighting on other objects.

A few potential options:
* Lamps with only colour animations should not be marked as movable
  * Risks causing animated lamps to not properly apply at runtime
  * Does not solve the light group issue for lamps with animated positions
* Lamps that are part of light groups should not be marked as movable
  * Not necessarily intuitive behaviour for artists
* Lamps should have a checkbox option to force not movable
  * Complicates the UI by adding clutter for rarely used options

**Comment by Hoikas** [comment]
Also keep in mind that Korman applies `kLPMovable` to any lamps attached to Python scripts. Any thoughts on that?

**Comment by dpogue** [comment]
Only to Python Scripts, or also Responders?

That might be an issue, they should probably follow the same rule as above (either not marking light group lamps or ignoring lamps that specifically ask to not be movable)

**Comment by Hoikas** [comment]
It looks like simply attaching a lamp to a group already has fairly major implications for how it's exported, so I think I will go with option 2. That is, if a lamp is in a group, then it will NOT be marked movable. If you're adding a lamp into a group, then you are basically saying, "I only want to affect these specific objects.", so marking them as movable (meaning, "apply me to all objects") doesn't really make sense in that context.
