### ISSUE TITLE
Use hashtable for find_key

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#27]
Korman's `find_key` implementation currently uses libHSPlasma's string search mechanism. Profiling shows this is somewhat slow, therefore, we should either rewrite the libHSPlasma code to use a hashtable or maintain a dict of keys in Korman itself.

**Comment by Deledrius** [comment]
Does @zrax's [String Theory](https://github.com/H-uru/libhsplasma/pull/76) improve this any?

**Comment by Hoikas** [comment]
Closed by 9601d6e
