### ISSUE TITLE
Footstep Regions Broken

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#281]
I just updated to the latest version of the main Korman repo as well as the new libHSPlasma files I received from Hoikas.

Something recent has broken the footstep regions. It exports the object, but the modifiers are not there. Note that this was still achieved after reverting all my hacks to the Korman master.

**Comment by DoobesURU** [comment]
So far, I have tested this on an export of Kirel as well as the version of Descent on which I've been working.

**Comment by Hoikas** [comment]
That's a pretty core feature that you've broken there, @Hoikas. Good job.

**Comment by DoobesURU** [comment]
> 
> 
> That's a pretty core feature that you've broken there, @Hoikas. Good job.

It's like you channeled _my_ coding ability or something. 😜
