### ISSUE TITLE
Nitpick: default buoyancy values.

### ISSUE THREAD

**Issue by Jrius** [H-uru/korman#291]
Something I noticed in my tests: the default upward buoyancy of 0.05 for swimming surfaces is extremely low - the avatar takes ages to float back up to the surface after a dive. Is there any reason for the current buoyancy values ? Ahnonay's defaults seem more reasonable IMHO.

**Comment by Hoikas** [comment]
I think I copied the default values out of PlasmaMax, but I'm not sure.
