### ISSUE TITLE
Python texture node needs named animation PointerProperty.

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#296]
I'm working on Vothol and using @Hazado 's xLakeLightCycle.py script [here](https://github.com/Hazado/Plasma/blob/LakeLightingProject/Scripts/Python/xLakeLightCycle.py) and noticed that the Python texture node can't reference named animations. Would it be a good idea to add this option to the node?

**Comment by Hoikas** [comment]
Fixed by #299.
