### ISSUE TITLE
"Ghost Reflection" in DCM Environment Maps

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#302]
This is something that has cropped up either recently or just went unnoticed until then, but at certain odd angles in third person view, an odd avatar "ghost" reflection can be seen in odd places.

When textures are off, it can be seen clearly in this Korman-exported version of K'veer taken by CalumTraveler:

![image](https://user-images.githubusercontent.com/40325124/141322855-3b11031b-5c19-4688-bc69-c8edfb230a96.png)

I've gone between the new version of K'veer and the original, trying to figure out what's different and making changes in PRPShop to more closely match Cyan's export...but nothing seems to get rid of the "ghost".

I should also note that this also crops up in the Pub as well, but went unnoticed given there's a lot of stuff on the floor blocking most of the view.

**Comment by Hoikas** [comment]
I think this is most likely an engine issue and not something we can fix in Korman.
