### ISSUE TITLE
Emissive by texture instead of material.

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#303]
Currently, Korman exports all textures in a material as emissive when it has `bm.emit > 0`.

What's needed for some Ages, such as K'veer and its ornate pillars, is to make the emit by texture instead.

I propose switching from using `if bm.emit > 0.0:` to using `if slot.use_map_emit:` to toggle emissive by texture. I've tried working the fix into the scripts myself, but it gets rather involved when adding `slot` parameters to the various `defs` and I'm not sure if I'm ripping things apart too much and if there's an easier solution. We can still use the int value from `bm.emit` for the amount of emissive light, which is how ZLZ imports it anyway.

**Comment by Hoikas** [comment]
That sounds reasonable. As you've noted, all of the `get_material_` color functions need to be updated to accept a texture slot to make that decision. Also, I think I would like to add a fallback so that if no slots have `use_map_emit` enabled, then all texture slots are emissive.

**Comment by DoobesURU** [comment]
> Also, I think I would like to add a fallback so that if no slots have `use_map_emit` enabled, then all texture slots are emissive.

Ah, good point. That way, we don't bork anyone's existing blend that's using the old method to great effect.

So if all textures get emit, then maybe they use the current `bm.emit` field and set it > 0.0. For textures, the use of `slot.use_map_emit' and its adjoining `slot.emit_factor` for the per-texture treatment.
