### ISSUE TITLE
Reapplying Scale to actors

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#305]
This has been an issue since the PyPRP days. Basically, if the transform scale of an actor object, such as a clickable, is something other that 1,1,1, weird things happen. Right now, reapplying scale using Ctrl+A fixes this, but could there be a way for Korman to do this automatically?

**Comment by Hoikas** [comment]
Korman should already be doing this under the hood. See: https://github.com/H-uru/korman/blob/2039b8a6d73b1833101f015c2982304aca907fbc/korman/exporter/physics.py#L66-L83

**Comment by Hoikas** [comment]
@DoobesURU do you have a sample blend that shows this issue?

**Comment by DoobesURU** [comment]
To be fair, this was told to me by someone, so the person might have a) been using an older version of Korman or b) using PyPRP or c) their Blender is wacky. Since I myself haven't encountered this in awhile, and given there's code that already solves this, I'll just close this issue. If it crops back up for some reason, then I can open another issue (or direct whoever tells me about it to do so).
