### ISSUE TITLE
Texture animation node cause export error

### ISSUE THREAD

**Issue by ametist365** [H-uru/korman#326]
I installed korman 0.13 with the installer and opened Elonin via the blender.exe in that korman folder. This Elonin blend is the same as used for latest export to Minkata and now works on MOULa. When I exported I got this error:
![korman013exporterror](https://user-images.githubusercontent.com/5249283/165945300-c8127c7f-c691-4313-be28-1784222a93de.jpg)
It is a texture animation on the fountainwater, triggered to start by a region
![eloninNode](https://user-images.githubusercontent.com/5249283/165945598-b2b6cab1-446d-41b1-b207-82f18d68826f.jpg)
If I set the Plasma Layer animation to Autostart and untick the region it works fine.

**Comment by ametist365** [comment]
'Animation Comand.014' is the node in the image. I tried with giving the object, the water mesh, an animation and put that node into the node tree as well, but the same error message came.

**Comment by Hoikas** [comment]
Can you share how the texture animation itself is set up?

**Comment by ametist365** [comment]
I decided to roll back to 0.11a for now.
