### ISSUE TITLE
LOC elements reorder each session with Blender

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#334]
While not really an issue on the user end, this is more for consideration for pull request/repo updates containing LOC files with multiple entries.

Each time an LOC file is exported, it jumbles up the various elements, which leads to unnecessary line changes each time the LOC is pushed to a new commit.

Could there be a way to order elements by when they were added, or perhaps more realistically, in alphabetical order based on element name?

EDIT: It's been determined that this reorganization only happens after quitting out of Blender, going back in, and re-exporting.

**Comment by DoobesURU** [comment]
Looking into this a bit more, it seems things only get rearranged when elements are either added or modified. This happens with both a full export and `Export Localization`.

**Comment by dpogue** [comment]
Sorting the keys alphabetically before writing the file seems like the best approach to ensure easier review of changes

**Comment by ZarothYe** [comment]
> Sorting the keys alphabetically before writing the file seems like the best approach to ensure easier review of changes
> 
> We might also want to do this in Plasma's plLocalizationEditor

Doesn't flipping a file through `plLocalizationEditor` already sort the sets and elements in alphabetical order? Would make sense to me to be consistent with this in the korman export.

**Comment by DoobesURU** [comment]
OK, I now see exactly what happens. If you export the LOC at any time during a session in Blender, the order stays the same, but when you quit out, restart Blender, _then_ try exporting localization again, _that's_ when it jumbles the elements. So maybe it's a Blender thing?
