### ISSUE TITLE
Korman plugin not enabled by default

### ISSUE THREAD

**Issue by Jrius** [H-uru/korman#344]
So Asteralium [brought to my attention](https://forum.guildofwriters.org/viewtopic.php?f=10&t=7355#p76229) that Blender-for-Korman doesn't automatically activate the Korman plugin. The [wiki](https://guildofwriters.org/wiki/Korman:Installation) doesn't mention manually activating it either, although [it did](https://guildofwriters.org/w/index.php?title=Korman:Installation&oldid=7533) at some point.

I don't recall Blender allows plugins to auto-enable themselves, but it probably has at least a whitelist of plugins that should be enabled by default. Could this be used for Korman ? Or should we just readd that section to the wiki ?

**Comment by Hoikas** [comment]
We should probably just Re-add the section to the wiki. I am hoping to make only minimal change to Blender that allow continued build support with new compilers. The program itself is too unwieldy, IMO, for me to want to claim any kind of maintainership aside from, "well, I build it for you."

**Comment by DoobesURU** [comment]
Yeah, that was my fault. I forgot that new installations of Blender inherit their settings across the board by default, so in my haste, I thought B4K did that particular legwork automatically. When I get time, I'll re-add all that to the installation tutorial.
