### ISSUE TITLE
SwimDockExit oneshot requires an "Object in Volume and Facing Detector"

### ISSUE THREAD

**Issue by Hazado** [H-uru/korman#360]
Right now when the SwimDockExit one shot is setup, the region will be anything that enters the region makes the oneshot happen.
This is problematic for the swim exits because it will can cause the avatar that just entered the water from the exit area to trigger the oneshot and exit the water immediately when they are facing away from the water.

To be clear I am talking about the plObjectInVolumeAndFacingDetector and not a facing detector and object in volume region

**Comment by Hoikas** [comment]
This is a good point - in general for region triggers (ie no clickable is involved), we should be using `plObjectInVolumeAndFacingDetector` instead of `plFacingConditionalModifier`. Korman's Logic Nodes currently assume regions with facing detectors are clickables.
