### ISSUE TITLE
Unsupported Operand Types when exporting.

### ISSUE THREAD

**Issue by Traveler263** [H-uru/korman#361]
Error Report on Writing Age Files after trying to export the age. First encountered when attempting to export Age Decals for footsteps and swimripples set to Multiple- second time after attempting an export with a parented object erroneously set to be inactive as a plasma object. EDIT: And a third time after having made that parented object export properly again. 
<img src="https://cdn.discordapp.com/attachments/282046743338811392/1075474932663865384/image.png">

**Comment by Traveler263** [comment]
I feel like this particular error report- if it's cropping up when a user sets something up improperly- needs to include what objects it is having issues with at the end of the export- or stop when it reaches a broken object and not complete the entire export setup only to stop at the final stage.

**Comment by Traveler263** [comment]
After repeatedly encountering this crash today, under varying circumstances, I'm beginning to suspect this isn't anything to do with my specific age changes and any appearance of my changes affecting things is just an illusion of randomness.

**Comment by dpogue** [comment]
hmm, this seems super weird, basically it's trying to join a folder path with an export filename. The way it's doing that assumes that both of those are Python Path objects and it's somehow getting called with Python Strings instead.

I don't know how or why that would happen, but it seems like there are probably some ways to be safer about handling this when it does happen.

**Comment by Hoikas** [comment]
Ok, while this is indeed a bug in Korman, what's crashing is a log message telling you that you have a problem.
```python
                report.warn("No data found for dependency file '{}'. It will not be copied into the export directory.",
                            str(i.dirname / i.filename), indent=1)
```

Korman can't find some file you're trying to use. Which file that is remains to be seen.
