### ISSUE TITLE
"Facing Target" node -> 90° tolerance

### ISSUE THREAD

**Issue by TheScarFr** [H-uru/korman#388]
There's an issue with the "Facing Target" node.
If I try with a "45°" tolerance, I have to check the "Directional" case, or clicking on the door button does nothing (it's clickable but it does nothing).
If I try with a "90°" tolerance, the door button isn't clickable, no matter if the "Directional" case is checked or not.

**Comment by Hoikas** [comment]
Can you provide a minimum viable reproduction blend of this?

**Comment by TheScarFr** [comment]
I will.

**Comment by Hoikas** [comment]
I see a handful of issues with how clickable facing conditions are being exported. I'm working on a fix, but it may be after the new year before I can fully test it.

**Comment by Hoikas** [comment]
This will be fixed in the next release of Korman.
