### ISSUE TITLE
Reset a kickable's location and rotation

### ISSUE THREAD

**Issue by TheScarFr** [H-uru/korman#389]
As a test, I tried to set a sphere as a kickable (it works) and to add to it an animation triggered by a clickable, my goal being to "reset" the sphere location and rotation when using the clickable.

If the animation keyframes are both set with the same location and rotation (keyframe 1 at 0 and keyframe 2 at 1), the kickable works, but not if the location is different (that being said, it doesn't have to be different).
In both cases, the sphere location and rotation aren't reseted when I use the clickable (it's only automaticaly reseted on relink if the sphere did fall through the Age).

Do you know if it will later be possible to reset a kickable's location and rotation by using a clickable (or entering in a region sensor); or to do it by using a custom python file, that will get the default location and rotation of a kickable, and set the clickable back to its default location and rotation when using a clickable (or entering in a region sensor)?

**Comment by Hoikas** [comment]
Animated kickables are not something we can feasibly support.

**Comment by TheScarFr** [comment]
Ok, thanks.
