### ISSUE TITLE
Responder Regions not working

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#393]
I think this has popped up somewhere in-between 0.14 and 0.15. Region sensors with associated responders either don't work or fast-forward to the end of the responder. Some examples I have noticed in testing:

1. The Link in/entry camera in Veelay Tsahvahn.
2. The music trigger for the lower floor in Chiso Preniv.
3. Some of the music triggers in Descent (specifically, the Eder Tomahn music).

**Comment by Hoikas** [comment]
Can you provide a small sample blend for this?

**Comment by DoobesURU** [comment]
> Can you provide a small sample blend for this?

I know I already gave you the link on Discord, but for posterity: https://www.dropbox.com/scl/fi/uykr1dkvo368dlzdw6ref/RgnRespTest.blend?rlkey=1oue6gs7hl39mtjp8r7fsr4tu&dl=0

**Comment by Hoikas** [comment]
After some discussion, we've determined that the logic nodes in question likely need some adjusting. I'm closing this, barring any other issues cropping up.
