### ISSUE TITLE
Remove `OrderedDict`

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#398]
`OrderedDict` was needed when we were using Blender 2.79b (with Python 3.5) to ensure that node sockets were consistently created in the same order as they were listed in Korman's code. As of Python 3.7, standard `dict` objects remember their order of insertion. Now that we require Blender for Korman or self-build Blenders using at least Python 3.7, we can remove `OrderedDict` and convert the node socket definitions to standard `dict` objects.

**Comment by 1Codealot** [comment]
Hi, I will do this later! :)

**Comment by Hoikas** [comment]
Closed by #400
