### ISSUE TITLE
Multiple clickables to one GUI PRP

### ISSUE THREAD

**Issue by DoobesURU** [H-uru/korman#405]
So I'm not sure if this is a Korman issue or a Plasma issue (or both), but after having played with the Guild decorations in Kirel and setting them to an SDL Int/Byte variable, I added new clickables for each Guild GUI popup for their new positions in the "minimal" deco setting.

While doing this, I've noticed that having multiple clickables (in this case, two apiece) pointing to one GUI PRP causes the client to crash. I may also be getting this intermittently in Chiso as well for some odd reason.

Deactivating the duplicate clickables keeps the client from crashing when Linking in, FWIW.

**Comment by Hoikas** [comment]
It's probably a Korman issue - if you're using the note popup modifier, I didn't expect for there to be multiple note popups pointing to the same GUI page. That *may* cause invalid data to be generated, if that's what you're doing.

**Comment by DoobesURU** [comment]
> It's probably a Korman issue - if you're using the note popup modifier, I didn't expect for there to be multiple note popups pointing to the same GUI page. That _may_ cause invalid data to be generated, if that's what you're doing.

Yep, that's exactly right. Multiple GUI note popup mods pointing to one GUI PRP.
