### ISSUE TITLE
Python packing

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#41]
Investigate the ability to create python packages as part of the age export process. This would possibly entail changing the exporter to take a directory and spewing the exported age data there**. See also #34 -- could possibly bundle some nonstandard scripts for PotS compatibility such as the journal template script.

*\* Related: could use Uru directories to parse GlobalAnimations to get animation marker points for OneShot and other logic nodes, preventing common errors.

**Comment by Deledrius** [comment]
This will probably be a necessary addition for distributing Ages easily.  Similar to #34, I'm unsure of the best way to reference the text.  Do we want to use the internal editor for storing Python scripts?  Or externally in a user-specified location?

Creating the packages themselves is fairly trivial.

--
I like the idea of parsing a data dir for the marker points.  If we want to parse locs too, then that solves the question in #34 as well.  We'll probably want a `Rescan` button in the helpers so external changes can be incorporated.  I have a partially-complete branch with a feature that scans the `.age` files for the purposes of exporting new Pages for an existing Age.  Perhaps these should all be consolidated?

**Comment by Hoikas** [comment]
Update... As part of debugging a crash in Doobes' Pub in Path of the Shell, I have determined that PotS will crash when PtGetAgeSDL is called if the AgeSDL blob is missing from the sav file. The creation of this blob has two basic requirements:
1. The presence of `<agename>.sdl` in the SDL directory.
2. The existence of the `<agename>` class in the `<agename>.py[c]` Python file.

(Recall of course that these SDL files use the age name by complete convention of course.  These notes are not intended to be a complete treatise on the functionality of `plPythonSDLModifier`s)

Therefore, this issue needs to be addressed. I see this playing out thusly:
* Update the Python File node to take links to Blender text note blocks.
    * In my testing, Blender will track the local file as well as keep a copy in memory. It notifies the user when it notices the files are out of sync.
    * Text files can be packed. Blender refers to this as making the files "internal".
* Write a new module in pykorlib that uses `ctypes` to load the game's python DLL (`cypython22.dll` or `python27.dll`) for compiling python source code.
    * Unfortunately, MOULa does not ship with a Python 2.3 DLL, AFAICT (but why are you targeting that anyway?)
    * A Python library selector can be added to the games panel for non-Windows systems.
* Write a new stage in the exporter for generating the `<agename>.pak`
    * ABM/PotS will go ahead and xTEA/wdys encrypt the pak and copy it over to the game directory.
    * For MOUL, we'll just want to copy the python files over to the game directory, I expect. This is because that client will only load `python.pak` and no other file.
    * Note to Self: don't forget the glue!
    * TBD: which files need to be packed? A simple solution would be to just skip packing if the filename begins with "x", but that seems like a hack. We could load the main `python.pak` and check for membership.
* If the age is exported with "Age SDL" as an option, Korman will automatically generate the python and SDL files.
    * SDL Version == 0
    * If an `<agename>.py` file is already present in the blendfile, we use it instead.
    * Remember that age names can contain characters that are illegal python identifiers. Will need to investigate if PotS can use runtime generated classes.
* Rework the exporter a bit to support having export warnings so stupid issues like a failure to compile the age python won't completely hose the export.
    * Would be nice to have an operator for packing the python separate of the age export process.
* Profit!

**Comment by Hoikas** [comment]
Closed by #128
