### ISSUE TITLE
Sitting Behavior issue

### ISSUE THREAD

**Issue by TheScarFr** [H-uru/korman#411]
In Korman 0.16:
If I use this Sitting Behavior Plasma Modifier (image 1), the export fails.
If I use this node tree instead of the Plasma Modifier (image 2), the export works.
Note: For both PotS and MOUL export.

Another little thing: When you rotate an object clockwise, let's say "90°", it's written "-90°" in the "Properties Editor > Object > Rotation" field; and vice-versa.

![plasma_modifier](https://github.com/H-uru/korman/assets/110847105/3889da49-1b30-4f2e-8761-9f811e257de5)
![node_tree](https://github.com/H-uru/korman/assets/110847105/1a1610e4-a150-421a-b04f-1a1ab990e068)

**Comment by Hoikas** [comment]
> If I use this Sitting Behavior Plasma Modifier (image 1), the export fails.

How does the export fail? Is there any error message shown?

**Comment by TheScarFr** [comment]
There's an very short and not helpful message, I'll tell you which one soon, probably tomorrow.

**Comment by TheScarFr** [comment]
![shot-20240427T181600](https://github.com/H-uru/korman/assets/110847105/ce497182-a8ea-4858-9694-46da43c3d246)
[StiltHouse01_export.log](https://github.com/H-uru/korman/files/15138731/StiltHouse01_export.log)
