### ISSUE TITLE
Subworlds

### ISSUE THREAD

**Issue by Hoikas** [H-uru/korman#46]
Add support for subworlds to Korman. This should include logic to handle exporting no arbitration volume sensors where available to avoid "falling through the floor" bugs. Also, to be investigated is the relevance of RidingAnimatedPhysicalDetectors for having dynamic avatar controllers.

**Comment by Hoikas** [comment]
Current observations: in PotS, subworlds were defined by `plHKSubWorld` object interfaces that allowed the artist to define a their own gravity vector 💥 . In CWE, subworlds are just scene object keys with no interface to gravity. PhysX *does* support arbitrary gravity. For the sake of being absolutely amazing (read: consistent), the first step here is to reintroduce the subworld gravity interface into CWE. This will entail refactoring the physical loader, unfortunately. Then, work can proceed on the Korman side of the equation.

**Comment by Deledrius** [comment]
Wow.  That sounds like a big task.  It would allow things like Relativity to be ported, though, so that's a great goal.

**Comment by Hoikas** [comment]
Currently blocking on #56

**Comment by Deledrius** [comment]
Anything still blocking this?

**Comment by Hoikas** [comment]
The Tsar's tight timetable at the moment...

**Comment by Deledrius** [comment]
Understood.

**Comment by Hoikas** [comment]
Closed by Korman 0.06
