### ISSUE TITLE
Animating lamp energy generates invalid PotS files

### ISSUE THREAD

**Issue by dpogue** [H-uru/korman#78]
Animating the energy on an omni lamp will create a plOmniSqApplicator, which is correct for MOUL but that class doesn't exist in PotS. The result is that libHSPlasma writes a null creatable (0x8000) for the AGApplicator and the exported files cause other tools to crash.

We should either only generate the OmniSqApplicator for MOUL-compatible exports, or have some step in libHSPlasma to filter out unsupported classes without writing nulls.

**Comment by dpogue** [comment]
An addition to this (that should probably spawn a libHSPlasma bug) is that PotS exports have the wrong controllers inside the applicator for some lighting:

PotS should have `plPointControllerChannel -> plSimplePosController -> plPoint3Controller`
MOUL should have `plPointControllerChannel -> plLeafController`

Korman is generating MOUL controllers and letting libHSPlasma downgrade them, but the downgrade process is producing `plPointControllerChannel -> plPoint3Controller` which crashes the game.

**Comment by Hoikas** [comment]
Note to self: for the addenum, libHSPlasma's `plLeafController::ExpandToKeyController()` needs to be corrected to produce the appropriate "Simple" controllers.

**Comment by Hoikas** [comment]
It appears that we will need to selectively remove inverse square omni light animations for PotS exports.

**Comment by Deledrius** [comment]
That sounds messy.

**Comment by Hoikas** [comment]
This can be closed when H-uru/libhsplasma#105 is merged.

**Comment by Hoikas** [comment]
Fixed by libHSPlasma merge
