### ISSUE TITLE
Ladder Modifier regions export incorrectly on PotS.

### ISSUE THREAD

**Issue by Deledrius** [H-uru/korman#93]
As [reported by J'Kla on the forum](https://forum.guildofwriters.org/viewtopic.php?f=10&t=6875), the new Ladder Modifiers do not export correctly for use in The Path of the Shell.  Both the top and bottom regions appear to be at the Age's origin instead of their correct positions.  I've confirmed the bug, but cannot determine the cause.

**Comment by Jrius** [comment]
Try adding mass to the collider along with the kPinned flag...
I didn't test it, but I've been working on understanding Plasma collisions for a while now B-)

**Comment by Deledrius** [comment]
I'll try that.  I did add the kPinned alone, but that didn't fix it.  Thanks for the suggestion!

**Comment by Deledrius** [comment]
This worked.  Thank you!

And now that I look, I see that's the one difference from the Er'cana Silo ladders I was comparing it to when trying to debug this.  Not sure how I missed it, but I must have just discounted the mass/friction/restitution settings as being relevant to what seemed to be a *position* problem.
